### PR TITLE
generalize RuleInvokerService to support 'pom' packaging

### PR DESCRIPTION
**Pull request by skylartd**
## Summary

Update plugin core to adapt with new version of the plugin that can support run archunit test on 'pom' packaging

## Details

Generalize RuleInvokerService so it can support run archunit test on 'pom' packaging.

## Checklist:

- [x] I've added tests for my code.

## Related issue : 
https://github.com/societe-generale/arch-unit-maven-plugin/issues/55

### CODE REVIEW

**Comment by vincent-fuchs** [comment]
Thanks for your contribution !

Can you please clarify the use case ? a pom packaging typically indicate that there's no code, but just build configuration to be reused in the submodules, so I don't see why we would want to run an archunit analysis at "pom level", rather than in each submodule.

you typically configure arch-unit-maven-plugin at the root level and then simply reference it in each submodule (or override the config if it needs to be different for that submodule).

**Comment by skylartd** [comment]
Hi vincent, 
The use case is for [LayerCheck](https://www.archunit.org/userguide/html/000_Index.html#_layer_checks:~:text=areAnnotatedWith(Transactional.class)-,4.6.%20Layer%20Checks,-layeredArchitecture()%0A%20%20%20%20.consideringAllDependencies()%0A%20%20%20%20.layer) in my project.

The structure of my project is like this:
- pom aggregator:
  - bootstrap module: which import all other modules
  - module A
  - module B
  - module C
  - module D

For example, I want to check that:
- Classes from module C should not use any class from other modules
- Classes from module A can only use classes in module B and C, not in module D
- Classes from module D can only use classes in module C.

This is achievable in a form of arch unit test in my bootstrap module (since arch unit test will scan both built classes and class from the jar in its dependencies).
But if I run the plugin in the bootstrap module, it does not aware of classes from the dependency imported by bootstrap (I've checked the core code and it only load built classes from either _target/classes_ or _target/test-classes_ - which is not ideal for layer testing, that's why I want to run it at the pom aggregator (which can load all classes from its sub-module)

**Comment by vincent-fuchs** [comment]
hi @skylartd , can't you achieve the same by managing dependencies between your modules ? I mean, if module C doesn't have a dependency to the other modules, then it won't be able to use their classes, and you don't need to check anything. Same for module A, if it doesn't declare any dependency to module D.  

do all your modules declare all other modules as dependencies ?

the way I understand it, LayerCheck is for packages **within** the same module, not across modules.

**Comment by skylartd** [comment]
Hi @vincent-fuchs ,

Yes, we can achieve the same thing by manually managing dependencies in our projects. But, in our company there're many microservices managed by different teams that should follow the references/recommended architecture but didn't.... and we figured out that with Archunit we can help teams to identify their violations and incrementally (with FreezingArchRule) refactor their code to meet the general recommended architecture.

**Comment by vincent-fuchs** [comment]
I understand your problem, but I think that's stretching it too far for `arch-unit-build-plugin-core`, sorry. 

A bunch of training session with the teams, explaining why it's not recommended to have all these cross referencing dependencies all over the place, and giving them ownership and the mandate to fix the issues, would be my recommendation here.. in my experience, fixing something "because you're told so", without understanding the rationale behind is actually a good way to make things worse

**Comment by skylartd** [comment]
Thank you for your suggestion, but I still think there's value if we can provide an ArchUnit test as architecture rule for all our microservices in the company the inherit from the same parent pom, it can:

- Help developer to identify their violations and provide them with a clearer picture on where they should improve their code, because even with training, sometimes we still make mistakes.
- Help new developer not to make mistake and to understand what they have dont incorrectly.
- With FreezingArchRule, it can provide a starting grounding point on incrementally improving instead of just forcing everybody to follow the rule mindlessly or because they're told to do so.
- And since it's only a maven plugin provided by the parent pom, feature team can always choose to disable and not run the recommended ArchUnit test, they still have their full ownership over their components.

I think with ArchUnit and this plugin, we can make rule/idea/architecture guide visible while still giving them the full control and responsibility of their own component.

**Comment by vincent-fuchs** [comment]
well, that's exactly what the plugin is for, and I've used it in many places like that (except the FreezingRule thing.. I've never used myself). But I am not willing to extend it to go beyond certain rules, like cross module dependencies and loading all modules from the pom level, while the analysis should (IMHO) happen at module level.  

Also, you can mix and match the tooling : for instance, I am using maven-enforcer with https://github.com/skuzzle/restrict-imports-enforcer-rule to prevent the use of certain imports. Maybe that's what you actually need for your initial requirement.

**Pull request closed without merging**
