### PR TITLE
Fix #66 - StringIndexOutOfBoundsException

### LINKED ISSUE #66: StringIndexOutOfBoundsException: String index out of range: -1 when file is scanned that contains the 'class' keyword only in comments
## Summary

It looks like [this issue](https://github.com/societe-generale/arch-unit-maven-plugin/issues/49) triggered with the Maven plugin, is caused by a general problem:
```
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.base/java.lang.String.substring(String.java:1837)
        at com.societegenerale.commons.plugin.service.JavaFileParser.extractClassName(JavaFileParser.java:124)
        at com.societegenerale.commons.plugin.service.JavaFileParser.parse(JavaFileParser.java:44)
        at com.societegenerale.commons.plugin.service.ExcludedPathsPreProcessor.determineClassNames(ExcludedPathsPreProcessor.java:194)
        at com.societegenerale.commons.plugin.service.ExcludedPathsPreProcessor.processExcludedPaths(ExcludedPathsPreProcessor.java:65)
        at com.societegenerale.commons.plugin.service.RuleInvokerService.<init>(RuleInvokerService.java:49)
        at com.societegenerale.commons.plugin.maven.ArchUnitMojo.execute(ArchUnitMojo.java:94)
        ... 13 common frames omitted
```

I think the core module should handle this case gracefully, and provide means to debug it, even if may not directly lead a resolution of the issue triggered in the Maven plugin.

## Type of Issue

It is a : 
 - [x] bug
 - [ ] request
 - [ ] question regarding the documentation

## Current Behavior

Passing file content that contain `class` only in a comment, leads to the process being aborted, with no additional information to resolve the issue.

## Expected Behavior

The core module should provide constructive feedback, and proceed with the next file.

## Steps to Reproduce (for bugs)

See https://github.com/societe-generale/arch-unit-maven-plugin/issues/49

## Your Environment

See https://github.com/societe-generale/arch-unit-maven-plugin/issues/49

### PR DESCRIPTION
**Pull request by Treehopper**
## Summary

See:
- https://github.com/societe-generale/arch-unit-maven-plugin/issues/49
- #66

- [x] I've added tests for my code.
- [ ] Documentation has been updated accordingly to this PR

## Related issue : 
- https://github.com/societe-generale/arch-unit-maven-plugin/issues/49
- #66

### CODE REVIEW

**Comment by Treehopper** [comment]
Looks like [Codacy is complaining about test method naming](https://app.codacy.com/gh/societe-generale/arch-unit-build-plugin-core/pullRequest?prid=9576007). I have no strong opinion on this. Just tried to match the existing style. Let me know if I should change it.

**Comment by Treehopper** [comment]
> Looks like [Codacy is complaining about test method naming](https://app.codacy.com/gh/societe-generale/arch-unit-build-plugin-core/pullRequest?prid=9576007). I have no strong opinion on this. Just tried to match the existing style. Let me know if I should change it.

I fixed the Codacy issue in an additional commit. Please feel free to merge as-is, or remove the commit.

**Comment by vincent-fuchs** [comment]
Thanks a lot, and sorry for the delay in reply. Looks OK to me, but I think we'll soon move to a proper library like https://github.com/forge/roaster to parse Java code : it will also be a good opportunity to make JDK 11 the minimum version.

**Comment by Treehopper** [comment]
@vincent-fuchs I see. Good to hear! Would it still be possible to get a release with the current implementation (including my fixes)?
Thanks!

**Comment by vincent-fuchs** [comment]
I just made a release of the core. Once it's available on Maven central, I will do a release of Maven and Gradle plugins

**Pull request merged**
